apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: boadgame-app-cluster
  region: us-east-1

nodeGroups:
- name: small-nodegroup
  instanceType: t2.micro
  desiredCapacity: 2

- name: medium-nodegroup
  instanceType: t2.small
  desiredCapacity: 2
